fix: make bat a needed requirement and enable the pager alwalys

diff --git a/gh-look b/gh-look
--- a/gh-look
+++ b/gh-look
@@ -27,7 +27,13 @@ PREVIEW_WINDOW_VISIBILITY="hidden"
 INITIAL_QUERY=""
 INITIAL_COMMENT_QUERY=""
 OUTPUT_SELECTION=""
-BAT_OR_CAT="cat"
+# it can happen, if a user defined "LESS" with the "-F" flag in its shell setup, e.g. LESS="-FK -j.5"
+# it will overwrite "bat --pager 'less -R' --paging always".
+# So the "-F" flag is removed, but the other options will remain the same.
+new_less="$(echo "$LESS" | sed 's/-F //;s/-F //;s/-F//;s/F//')"
+export LESS=$new_less
+LANG_BAT_SETUP="bat --pager 'less -R' --paging always --color always --style plain --language"
+
 # for better speed
 CACHE_TIME="20s"
 # minimum required fzf version, using "become(...)"
@@ -88,6 +94,7 @@ _load_indicator() {
 		echo -ne "\r$i"
 		sleep "${2:-"0.2"}"
 	done
+	echo
 }
 
 # return the emoji from its corresponding string name
@@ -210,10 +217,10 @@ fzf_issue_function() {
 	OUTPUT_SELECTION=$(FZF_DEFAULT_COMMAND="(grep -q A <$SCRATCH_FILE && $GH_ISSUE_COMMAND --cache ${1:-$CACHE_TIME} --raw-field filter=\"$SORTING_ORDER type:issue repo:$OWNER_REPO_NAME $INITIAL_QUERY \" || $GH_ISSUE_COMMAND --cache ${1:-$CACHE_TIME} --raw-field filter=\"$SORTING_ORDER type:issue repo:$OWNER_REPO_NAME state:open $INITIAL_QUERY \") || true" \
 		_fzf_basic_options --disabled --header-lines 3 --with-nth 2.. \
 		--prompt "$INITIAL_ISSUE_PROMPT" \
-		--query "$INITIAL_QUERY" --preview "sleep 0.35; $GH_ISSUE_PREVIEW | $BAT_OR_CAT" \
+		--query "$INITIAL_QUERY" --preview "sleep 0.35; $GH_ISSUE_PREVIEW | $LANG_BAT_SETUP md" \
 		--bind "change:first+reload-sync:sleep 0.25; (grep -q A <$SCRATCH_FILE && $GH_ISSUE_COMMAND --cache $CACHE_TIME --raw-field filter=\"$SORTING_ORDER type:issue repo:$OWNER_REPO_NAME \"{q} || $GH_ISSUE_COMMAND --cache $CACHE_TIME --raw-field filter=\"$SORTING_ORDER type:issue repo:$OWNER_REPO_NAME state:open \"{q}) || true" \
 		--bind "?:toggle-preview+change-preview:echo '$(help_issue_function)'" \
-		--bind "tab:toggle-preview+change-preview:sleep 0.35; $GH_ISSUE_PREVIEW | $BAT_OR_CAT" \
+		--bind "tab:toggle-preview+change-preview:sleep 0.35; $GH_ISSUE_PREVIEW | $LANG_BAT_SETUP md" \
 		--bind "ctrl-a:rebind(change)+change-prompt(Issues ◉ [$OWNER_REPO_NAME] > )+disable-search+execute-silent(echo A >$SCRATCH_FILE)+reload-sync:$GH_ISSUE_COMMAND --cache $CACHE_TIME --raw-field filter=\"$SORTING_ORDER type:issue repo:$OWNER_REPO_NAME \"{q} || true" \
 		--bind "ctrl-b:execute-silent(gh issue view {2} --web --repo $OWNER_REPO_NAME)" \
 		--bind $'ctrl-f:unbind(change)+enable-search+clear-query+change-prompt(\e[1;93mFUZZY SEARCH'" [$OWNER_REPO_NAME] > )" \
@@ -358,9 +365,9 @@ fzf_issue_comment_function() {
 	OUTPUT_SELECTION=$(FZF_DEFAULT_COMMAND="$GH_ISSUE_COMMENTS_COMMAND --cache ${1:-$CACHE_TIME} --raw-field owner=${OWNER_REPO_NAME%/*} --raw-field name=${OWNER_REPO_NAME#*/} --field number=$TICKET_NUMBER" \
 		_fzf_basic_options --header-lines 6 --with-nth 3.. \
 		--query "$INITIAL_COMMENT_QUERY" --prompt $'\e[1;94m'"Issue 💬 [$OWNER_REPO_NAME] > " \
-		--preview-window "+5:~5" --preview "$GH_COMMENTS_PREVIEW | $BAT_OR_CAT" \
+		--preview-window "+5:~5" --preview "$GH_COMMENTS_PREVIEW | $LANG_BAT_SETUP md" \
 		--bind "?:toggle-preview+change-preview:echo '$(help_issue_comment_function)'" \
-		--bind "tab:toggle-preview+change-preview:$GH_COMMENTS_PREVIEW | $BAT_OR_CAT" \
+		--bind "tab:toggle-preview+change-preview:$GH_COMMENTS_PREVIEW | $LANG_BAT_SETUP md" \
 		--bind "ctrl-b:execute-silent(open https://github.com/$OWNER_REPO_NAME/issues/$TICKET_NUMBER#issuecomment-{2})" \
 		--bind "ctrl-t:execute-silent($GH_ADD_REACTION --raw-field id={1} --raw-field emoji=$REACTION_EMOJI)+reload-sync:$GH_ISSUE_COMMENTS_COMMAND --raw-field owner=${OWNER_REPO_NAME%/*} --raw-field name=${OWNER_REPO_NAME#*/} --field number=$TICKET_NUMBER || true" \
 		--bind "ctrl-u:execute-silent($GH_REMOVE_REACTION --raw-field id={1} --raw-field emoji=$REACTION_EMOJI)+reload-sync:$GH_ISSUE_COMMENTS_COMMAND --raw-field owner=${OWNER_REPO_NAME%/*} --raw-field name=${OWNER_REPO_NAME#*/} --field number=$TICKET_NUMBER || true" \
@@ -495,10 +502,10 @@ fzf_pr_function() {
 	OUTPUT_SELECTION=$(FZF_DEFAULT_COMMAND="(grep -q A <$SCRATCH_FILE && $GH_PR_COMMAND --cache ${1:-$CACHE_TIME} --raw-field filter=\"$SORTING_ORDER type:pr repo:$OWNER_REPO_NAME $INITIAL_QUERY \" || $GH_PR_COMMAND --cache ${1:-$CACHE_TIME} --raw-field filter=\"$SORTING_ORDER type:pr repo:$OWNER_REPO_NAME state:open $INITIAL_QUERY \") || true" \
 		_fzf_basic_options --disabled --header-lines 3 --with-nth 2.. \
 		--prompt "$INITIAL_PR_PROMPT" \
-		--query "$INITIAL_QUERY" --preview "sleep 0.35; $GH_PR_PREVIEW | $BAT_OR_CAT" \
+		--query "$INITIAL_QUERY" --preview "sleep 0.35; $GH_PR_PREVIEW | $LANG_BAT_SETUP md" \
 		--bind "change:first+reload-sync:sleep 0.25; (grep -q A <$SCRATCH_FILE && $GH_PR_COMMAND --cache $CACHE_TIME --raw-field filter=\"$SORTING_ORDER type:pr repo:$OWNER_REPO_NAME \"{q} || $GH_PR_COMMAND --cache $CACHE_TIME --raw-field filter=\"$SORTING_ORDER type:pr repo:$OWNER_REPO_NAME state:open \"{q}) || true" \
 		--bind "?:toggle-preview+change-preview:echo '$(help_pr_function)'" \
-		--bind "tab:toggle-preview+change-preview:sleep 0.35; $GH_PR_PREVIEW | $BAT_OR_CAT" \
+		--bind "tab:toggle-preview+change-preview:sleep 0.35; $GH_PR_PREVIEW | $LANG_BAT_SETUP md" \
 		--bind "ctrl-a:rebind(change)+change-prompt(Pull Requests  [$OWNER_REPO_NAME] > )+disable-search+execute-silent(echo A >$SCRATCH_FILE)+reload-sync:$GH_PR_COMMAND --cache $CACHE_TIME --raw-field filter=\"$SORTING_ORDER type:pr repo:$OWNER_REPO_NAME \"{q} || true" \
 		--bind "ctrl-b:execute-silent(gh pr view {2} --web --repo $OWNER_REPO_NAME)" \
 		--bind $'ctrl-f:unbind(change)+enable-search+clear-query+change-prompt(\e[1;93mFUZZY SEARCH'" [$OWNER_REPO_NAME] > )" \
@@ -610,9 +617,9 @@ fzf_pr_comment_function() {
 	OUTPUT_SELECTION=$(FZF_DEFAULT_COMMAND="$GH_PR_COMMENTS_COMMAND --cache ${1:-$CACHE_TIME} --raw-field owner=${OWNER_REPO_NAME%/*} --raw-field name=${OWNER_REPO_NAME#*/} --field number=$TICKET_NUMBER" \
 		_fzf_basic_options --header-lines 6 --with-nth 3.. \
 		--prompt $'\e[1;94m'"Pull Request 💬 [$OWNER_REPO_NAME] > " \
-		--preview-window "+5:~5" --preview "$GH_COMMENTS_PREVIEW | $BAT_OR_CAT" \
+		--preview-window "+5:~5" --preview "$GH_COMMENTS_PREVIEW | $LANG_BAT_SETUP md" \
 		--bind "?:toggle-preview+change-preview:echo '$(help_pr_comment_function)'" \
-		--bind "tab:toggle-preview+change-preview:$GH_COMMENTS_PREVIEW | $BAT_OR_CAT" \
+		--bind "tab:toggle-preview+change-preview:$GH_COMMENTS_PREVIEW | $LANG_BAT_SETUP md" \
 		--bind "ctrl-b:execute-silent(open https://github.com/$OWNER_REPO_NAME/pull/$TICKET_NUMBER#issuecomment-{2})" \
 		--bind "ctrl-d:toggle-preview+change-preview(gh pr diff $TICKET_NUMBER --repo $OWNER_REPO_NAME"$' | if type -p delta >/dev/null; then delta --width ${FZF_PREVIEW_COLUMNS:-$COLUMNS}; else cat; fi)' \
 		--bind "ctrl-t:execute-silent($GH_ADD_REACTION --raw-field id={1} --raw-field emoji=$REACTION_EMOJI)+reload-sync:$GH_PR_COMMENTS_COMMAND --raw-field owner=${OWNER_REPO_NAME%/*} --raw-field name=${OWNER_REPO_NAME#*/} --field number=$TICKET_NUMBER || true" \
@@ -659,7 +666,7 @@ ${WHITE_BOLD}Symbols${COLOR_RESET}
 
 ${WHITE_BOLD}Hotkeys${COLOR_RESET}
   ${GREEN_NORMAL}?        ${COLOR_RESET}  Toggle help
-  ${GREEN_NORMAL}enter    ${COLOR_RESET}  See logs
+  ${GREEN_NORMAL}enter    ${COLOR_RESET}  See logs, press "q" to return
   ${GREEN_NORMAL}tab      ${COLOR_RESET}  Toggle preview
   ${GREEN_NORMAL}shift+tab${COLOR_RESET}  Change preview window size
   ${GREEN_NORMAL}ctrl+a   ${COLOR_RESET}  Attached artifacts are downloaded
@@ -683,24 +690,50 @@ fzf_workflow_run_function() {
 		_fzf_basic_options --header-lines 1 --with-nth 4.. \
 		--header $'\n? Help · esc Quit\n\n' \
 		--prompt "$INITIAL_WORKFLOW_PROMPT 👀 ${UPDATE_TIME}s > " \
+		--query "$INITIAL_QUERY" \
 		--preview "gh run view {1} --repo $OWNER_REPO_NAME" \
+		--bind "tab:toggle-preview+change-preview:gh run view {1} --repo $OWNER_REPO_NAME" \
 		--bind "?:toggle-preview+change-preview:echo '$(help_workflow_run_function)'" \
 		--bind "load:reload-sync:sleep $UPDATE_TIME;$GH_WORKFLOWS_COMMAND || true" \
-		--bind "enter:execute:if grep -Eq 'in_progress|queued' <<<{3}; then gh run watch --repo $OWNER_REPO_NAME; else GH_PAGER=\"bat -pl log\" gh run view --log {1} --repo $OWNER_REPO_NAME; fi" \
 		--bind "ctrl-a:become(gh run download {1} --repo $OWNER_REPO_NAME)+reload-sync:$GH_WORKFLOWS_COMMAND || true" \
 		--bind "ctrl-b:execute-silent:open {2}" \
 		--bind "ctrl-d:execute-silent(gh run delete {1} --repo $OWNER_REPO_NAME)+reload-sync:$GH_WORKFLOWS_COMMAND || true" \
-		--bind "ctrl-f:execute:GH_PAGER=\"bat -pl log\" gh run view --log-failed {1} --repo $OWNER_REPO_NAME" \
 		--bind "ctrl-r:rebind(load)+change-prompt($INITIAL_WORKFLOW_PROMPT 👀 ${UPDATE_TIME}s > )+reload-sync:$GH_WORKFLOWS_COMMAND || true" \
 		--bind "ctrl-u:unbind(load)+change-prompt:$INITIAL_WORKFLOW_PROMPT > " \
 		--bind "ctrl-x:execute-silent(gh run cancel {1} --repo $OWNER_REPO_NAME)+reload-sync:$GH_WORKFLOWS_COMMAND || true" \
-		--expect "shift-up") || true
+		--expect "ctrl-f,enter,shift-up") || true
 
+	printed_query="$(sed 1q <<<"$OUTPUT_SELECTION")"
 	expected_key="$(sed '1d;3d' <<<"$OUTPUT_SELECTION")"
+	output_id="$(sed '1d;2d' <<<"$OUTPUT_SELECTION" | awk '{print $1}')"
+	output_status="$(sed '1d;2d' <<<"$OUTPUT_SELECTION" | awk '{print $3}')"
 	# reset the variable
 	OUTPUT_SELECTION=""
 	case "$expected_key" in
-	shift-up) fzf_pr_function ;;
+	enter)
+		if grep -Eq 'in_progress|queued' <<<"$output_status"; then
+			gh run watch --repo "$OWNER_REPO_NAME"
+		elif ! gh run view --log "$output_id" --repo "$OWNER_REPO_NAME" &>/dev/null; then
+			_load_indicator $'No logs found\nRestarting ...'
+		else
+			GH_PAGER="$LANG_BAT_SETUP log" gh run view --log "$output_id" --repo "$OWNER_REPO_NAME"
+		fi
+		INITIAL_QUERY="$printed_query"
+		fzf_workflow_run_function
+		;;
+	ctrl-f)
+		if ! gh run view --log-failed "$output_id" --repo "$OWNER_REPO_NAME" &>/dev/null; then
+			_load_indicator $'No failed logs found\nRestarting ...'
+		else
+			GH_PAGER="$LANG_BAT_SETUP log" gh run view --log-failed "$output_id" --repo "$OWNER_REPO_NAME"
+		fi
+		INITIAL_QUERY="$printed_query"
+		fzf_workflow_run_function
+		;;
+	shift-up)
+		INITIAL_QUERY=""
+		fzf_pr_function
+		;;
 	esac
 }
 
@@ -897,15 +930,15 @@ if [ $# = 0 ]; then
 	_die_with_octocat "Invalid command:" "$(help_general_function)"
 else
 	############# Check needed programs installed #############
+	if ! command -v bat >/dev/null; then
+		_die_with_octocat "Bat was not found." "https://github.com/sharkdp/bat"
+	fi
 	if ! command -v fzf >/dev/null; then
-		_die_with_octocat "Fuzzy finder (fzf) was not found."
+		_die_with_octocat "Fuzzy finder (fzf) was not found." "https://github.com/junegunn/fzf"
 	fi
 	USER_FZF_VERSION="$(fzf --version | awk '{print $1}')"
 	if [ "$(_version_number $MIN_FZF_VERSION)" -gt "$(_version_number "$USER_FZF_VERSION")" ]; then
 		_die_with_octocat "Minimum required \`fzf\` version is: $MIN_FZF_VERSION (found: $USER_FZF_VERSION)"
-	fi
-	if command -v bat >/dev/null; then
-		BAT_OR_CAT="bat --color always --language md --style plain"
 	fi
 
 	############# Check needed scratch file exits and writeable #############
