Error function - die_with_octocat

diff --git a/gh-look b/gh-look
--- a/gh-look
+++ b/gh-look
@@ -26,6 +26,12 @@ _fzf_basic_options() {
 		--preview-window "$PREVIEW_WINDOW_VISIBILITY:wrap:right:50%:border-left" "$@"
 }
 
+die_with_octocat() {
+	GH_PAGER="cat" gh api octocat
+	printf "\e[1;91m[%s] < ERROR > %s\e[0m\n" "$(date +"%H:%M:%S")" "$@"
+	exit 1
+}
+
 ############# Manual #############
 HELP_GENERAL='cat <<<"
 gh look [Command] [-Flags] [Search term]
@@ -371,7 +377,7 @@ _fzf_pr() {
 		--bind "ctrl-a:rebind(change)+change-prompt(Pull Requests  [$OWNER_REPO_NAME] > )+disable-search+execute-silent(echo A >$SCRATCH_FILE)+reload:$GH_PR_COMMAND --cache $CACHE_TIME --raw-field filter=\"$SORTING_ORDER type:pr repo:$OWNER_REPO_NAME \"{q} || true" \
 		--bind "ctrl-b:execute-silent(gh pr view {2} --web --repo $OWNER_REPO_NAME)" \
 		--bind $'ctrl-f:unbind(change)+enable-search+clear-query+change-prompt(\e[1;93mFUZZY SEARCH'" [$OWNER_REPO_NAME] > )" \
-		--bind "ctrl-d:toggle-preview+change-preview(gh pr diff {2} --repo $OWNER_REPO_NAME"$' | if type delta &>/dev/null; then delta --width ${FZF_PREVIEW_COLUMNS:-$COLUMNS}; else cat; fi)' \
+		--bind "ctrl-d:toggle-preview+change-preview(gh pr diff {2} --repo $OWNER_REPO_NAME"$' | if type -p delta >/dev/null; then delta --width ${FZF_PREVIEW_COLUMNS:-$COLUMNS}; else cat; fi)' \
 		--bind $'ctrl-o:rebind(change)+change-prompt(\e[1;92mOPEN Pull Requests '" [$OWNER_REPO_NAME] > )+disable-search+execute-silent(echo B >$SCRATCH_FILE)+reload:$GH_PR_COMMAND --cache $CACHE_TIME --raw-field filter=\"$SORTING_ORDER type:pr repo:$OWNER_REPO_NAME state:open \"{q} || true" \
 		--bind "ctrl-r:reload:(grep -q A <$SCRATCH_FILE && $GH_PR_COMMAND --raw-field filter=\"$SORTING_ORDER type:pr repo:$OWNER_REPO_NAME \"{q} || $GH_PR_COMMAND --raw-field filter=\"$SORTING_ORDER type:pr repo:$OWNER_REPO_NAME state:open \"{q}) || true" \
 		--bind "ctrl-t:execute-silent($GH_ADD_REACTION --raw-field id={1} --raw-field emoji=$REACTION_EMOJI)+reload:(grep -q A <$SCRATCH_FILE && $GH_PR_COMMAND --raw-field filter=\"$SORTING_ORDER type:pr repo:$OWNER_REPO_NAME \"{q} || $GH_PR_COMMAND --raw-field filter=\"$SORTING_ORDER type:pr repo:$OWNER_REPO_NAME state:open \"{q}) || true" \
@@ -461,7 +467,7 @@ esc      │ Return to Pull Request list"'
 		--bind "?:toggle-preview+change-preview:$HELP_PR_COMMENT_SECTION" \
 		--bind "tab:toggle-preview+change-preview:$GH_COMMENTS_PREVIEW | $BAT_OR_CAT" \
 		--bind "ctrl-b:execute-silent(open https://github.com/$OWNER_REPO_NAME/pull/$PR_NUMBER#issuecomment-{2})" \
-		--bind "ctrl-d:toggle-preview+change-preview(gh pr diff $PR_NUMBER --repo $OWNER_REPO_NAME"$' | if type delta &>/dev/null; then delta --width ${FZF_PREVIEW_COLUMNS:-$COLUMNS}; else cat; fi)' \
+		--bind "ctrl-d:toggle-preview+change-preview(gh pr diff $PR_NUMBER --repo $OWNER_REPO_NAME"$' | if type -p delta >/dev/null; then delta --width ${FZF_PREVIEW_COLUMNS:-$COLUMNS}; else cat; fi)' \
 		--bind "ctrl-t:execute-silent($GH_ADD_REACTION --raw-field id={1} --raw-field emoji=$REACTION_EMOJI)+reload:$GH_PR_COMMENTS_COMMAND --raw-field owner=${OWNER_REPO_NAME%/*} --raw-field name=${OWNER_REPO_NAME#*/} --field number=$PR_NUMBER || true" \
 		--bind "ctrl-u:execute-silent($GH_REMOVE_REACTION --raw-field id={1} --raw-field emoji=$REACTION_EMOJI)+reload:$GH_PR_COMMENTS_COMMAND --raw-field owner=${OWNER_REPO_NAME%/*} --raw-field name=${OWNER_REPO_NAME#*/} --field number=$PR_NUMBER || true" \
 		--expect "ctrl-x,esc") || true
@@ -558,8 +564,7 @@ _fzf_search() {
 		INITIAL_QUERY=""
 		OWNER_REPO_NAME=$(sed 1d <<<"${SEARCH_OUTPUT}" | awk '{print $1}')
 		if [ -z "$OWNER_REPO_NAME" ]; then
-			git ls-remote --get-url 2>/dev/null 1>&2 || exit 1
-			OWNER_REPO_NAME="$(gh api graphql --cache 1h --field owner=:owner --field name=:repo --raw-field query=$'query ($owner: String!, $name: String!) { repository(owner: $owner, name: $name) { nameWithOwner }}' --jq '.[].repository.nameWithOwner')"
+			OWNER_REPO_NAME="$(gh api graphql --cache 1h --field owner=:owner --field name=:repo --raw-field query=$'query ($owner: String!, $name: String!) { repository(owner: $owner, name: $name) { nameWithOwner }}' --jq '.[].repository.nameWithOwner' 2>/dev/null || echo "cli/cli")"
 		fi
 		_fzf_issue 0s
 		;;
@@ -673,13 +678,11 @@ GH_REMOVE_REACTION=$'gh api graphql --silent --raw-field query=\'mutation($id: I
 GH_COMMENTS_PREVIEW=$'gh api graphql --raw-field id={1} --raw-field query=\'query($id: ID! ){node(id: $id) {... on Comment { author{login} body createdAt viewerDidAuthor} ... on Reactable { reactionGroups { content viewerHasReacted reactors(last: 4) { nodes {... on User { login }} totalCount }}}}}\' --template \'{{- $prefix := .data.node -}}{{- $author := "[DELETED_USER]" -}}{{- if $prefix.author -}}{{- $author = $prefix.author.login -}}{{- end -}}{{- $authorColor := "cyan+hb" -}}{{- if $prefix.viewerDidAuthor -}}{{- $authorColor = "yellow+bh" -}}{{- end -}}{{- tablerow  ("◥■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■◤"| color "gray+d") -}}{{- tablerender -}}{{- tablerow ($author | color $authorColor) (timeago $prefix.createdAt | color "white+bh") -}}{{- tablerender -}}{{- range $prefix.reactionGroups -}}{{ $emoji := .content }}{{ if eq .content "CONFUSED" }}{{ $emoji = "😕" }}{{ else if eq .content "EYES" }}{{ $emoji = "👀" }}{{ else if eq .content "HEART" }}{{ $emoji = "💖" }}{{ else if eq .content "HOORAY" }}{{ $emoji = "🎉" }}{{ else if eq .content "LAUGH" }}{{ $emoji = "😄" }}{{ else if eq .content "THUMBS_DOWN" }}{{ $emoji = "👎" }}{{ else if eq .content "THUMBS_UP" }}{{ $emoji = "👍" }}{{ else if eq .content "ROCKET" }}{{ $emoji = "🚀" }}{{ end }}{{ if gt .reactors.totalCount 0.0 }}{{ $emojiGiver := pluck "login" .reactors.nodes | join ", " | color "green+d" }}{{ if gt (pluck "login" .reactors.nodes | len ) 3 }}{{- /* NOTE: number of names limited */ -}}{{ $emojiGiver = slice (pluck "login" .reactors.nodes) 1 | join ", " | printf "%s, ..." | color "green+d" }}{{end}}{{- $emojiTotal := .reactors.totalCount | color "green+bd" -}}{{- if .viewerHasReacted -}}{{- $emojiTotal = .reactors.totalCount | color "yellow+bh" -}}{{- end -}}{{- tablerow (printf "%s %s" $emojiTotal $emoji) $emojiGiver -}}{{- tablerender -}}{{- end -}}{{- end }}{{- tablerow  ("‥‥‥‥‥‥‥‥‥‥‥‥‥‥‥‥‥‥‥‥‥‥‥‥‥‥‥‥‥"| color "gray+d") -}}{{- tablerender -}}{{- tablerow "" -}}{{- tablerender -}}{{- $prefix.body -}}\''
 
 if [ $# = 0 ]; then
-	bash -c "$HELP_GENERAL"
-	exit 1
+	die_with_octocat "Invalid command: $(bash -c "$HELP_GENERAL")"
 else
 	############# Check needed programs installed #############
 	if ! command -v fzf >/dev/null; then
-		echo "Missing: fzf"
-		exit 1
+		die_with_octocat "Fuzzy finder (fzf) was not found."
 	fi
 	if command -v bat >/dev/null; then
 		BAT_OR_CAT="bat --color always --language md --style plain"
@@ -693,8 +696,7 @@ else
 		touch "$SCRATCH_FILE" 2>/dev/null || echo "Not allowed creating $SCRATCH_FILE"
 	fi
 	if [ ! -w "$SCRATCH_FILE" ]; then
-		echo Not allowed writing to "$SCRATCH_FILE"
-		exit 1
+		die_with_octocat "Not allowed writing to: $SCRATCH_FILE"
 	fi
 fi
 
@@ -709,27 +711,21 @@ while [ $# -gt 0 ]; do
 				if [[ "$OPTARG" =~ ^[0-9]+[smh]$ ]]; then
 					CACHE_TIME="$OPTARG"
 				else
-					gh api octocat
-					echo "Search help, invalid cache time: $OPTARG !!!"
-					exit 1
+					die_with_octocat "Invalid cache time: $OPTARG"
 				fi
 				;;
 			e)
 				if [[ "CONFUSED EYES HEART HOORAY LAUGH THUMBS_DOWN THUMBS_UP ROCKET" =~ $OPTARG ]]; then
 					REACTION_EMOJI="$OPTARG"
 				else
-					gh api octocat
-					echo "!!! Search help, invalid emoji: $OPTARG"
-					exit 1
+					die_with_octocat "Invalid emoji: $OPTARG"
 				fi
 				;;
 			o)
 				if [[ "$OPTARG" =~ ^[A-Za-z-]{7,}$ ]]; then
 					SORTING_ORDER="sort:$OPTARG"
 				else
-					gh api octocat
-					echo "Search help, invalid sort order: $OPTARG !!!"
-					exit 1
+					die_with_octocat "Invalid sort order: $OPTARG"
 				fi
 				;;
 			r)
@@ -738,21 +734,16 @@ while [ $# -gt 0 ]; do
 				if [[ "$OPTARG" =~ ^[^:/]+/[^:/]+$ ]]; then
 					OWNER_REPO_NAME="$OPTARG"
 				else
-					gh api octocat
-					echo "!!! Respect the syntax: gh look {issue,pr} -R OWNER/REPO"
-					exit 1
+					die_with_octocat "Respect the syntax: gh look {issue,pr} -R OWNER/REPO"
 				fi
 				if ! gh api --silent repos/"$OWNER_REPO_NAME" 2>/dev/null; then
-					gh api octocat
-					echo "No GitHub repo called $OWNER_REPO_NAME !!!"
-					exit 1
+					die_with_octocat "No GitHub repo called: $OWNER_REPO_NAME"
 				fi
 				;;
 			w) PREVIEW_WINDOW_VISIBILITY="nohidden" ;;
 			*)
-				grep -q "issue" <<<"$COMMAND_ARG" && bash -c "$HELP_ISSUE_SECTION"
-				grep -q "pr" <<<"$COMMAND_ARG" && bash -c "$HELP_PR_SECTION"
-				exit 0
+				grep -q "issue" <<<"$COMMAND_ARG" && die_with_octocat "Invalid command: $(bash -c "$HELP_ISSUE_SECTION")"
+				grep -q "pr" <<<"$COMMAND_ARG" && die_with_octocat "Invalid command: $(bash -c "$HELP_PR_SECTION")"
 				;;
 			esac
 		done
@@ -761,7 +752,7 @@ while [ $# -gt 0 ]; do
 		INITIAL_QUERY="$*"
 		if [ -z "$OWNER_REPO_NAME" ]; then
 			# if the OWNER_REPO_NAME is not set yet, check if the repo has a remote and assign the variable
-			git ls-remote --get-url 2>/dev/null 1>&2 || exit 1
+			git ls-remote --get-url >/dev/null 2>&1 || die_with_octocat "No remote git repo found"
 			# local alternative, but requires Perl-compatible regular expressions (PCREs)
 			# git remote -v | grep -m 1 -oP '(?<=\:).+(?=\.)'
 			OWNER_REPO_NAME="$(gh api graphql --cache 1h --field owner=:owner --field name=:repo --raw-field query=$'query ($owner: String!, $name: String!) { repository(owner: $owner, name: $name) { nameWithOwner }}' --jq '.[].repository.nameWithOwner')"
@@ -779,15 +770,12 @@ while [ $# -gt 0 ]; do
 				if [[ "$OPTARG" =~ ^[0-9]+[smh]$ ]]; then
 					CACHE_TIME="$OPTARG"
 				else
-					gh api octocat
-					echo "Search help, invalid cache time: $OPTARG !!!"
-					exit 1
+					die_with_octocat "Invalid cache time: $OPTARG"
 				fi
 				;;
 			w) PREVIEW_WINDOW_VISIBILITY="nohidden" ;;
 			*)
-				bash -c "$HELP_SEARCH_SECTION"
-				exit 1
+				die_with_octocat "Invalid command: $(bash -c "$HELP_SEARCH_SECTION")"
 				;;
 			esac
 		done
@@ -804,9 +792,7 @@ while [ $# -gt 0 ]; do
 				if [[ "$OPTARG" =~ ^[0-9]+[smh]$ ]]; then
 					CACHE_TIME="$OPTARG"
 				else
-					gh api octocat
-					echo "Search help, invalid cache time: $OPTARG !!!"
-					exit 1
+					die_with_octocat "Invalid cache time: $OPTARG"
 				fi
 				;;
 			U)
@@ -814,20 +800,16 @@ while [ $# -gt 0 ]; do
 				if [[ "$OPTARG" =~ ^[^:/]+$ ]]; then
 					USER_NAME="$OPTARG"
 				else
-					echo "!!! Respect the syntax: gh look star -U USER"
-					exit 1
+					die_with_octocat "Respect the syntax: gh look star -U USER"
 				fi
 				# gh api --silent users/... would be shorter, but would result in a false positive for organizations
 				if ! gh api graphql --silent --raw-field USER_NAME="$USER_NAME" --raw-field query=$'query ($USER_NAME: String!) { user(login: $USER_NAME) { login }}' 2>/dev/null; then
-					gh api octocat
-					echo "No USER called $USER_NAME !!!"
-					exit 1
+					die_with_octocat "No USER called: $USER_NAME"
 				fi
 				;;
 			w) PREVIEW_WINDOW_VISIBILITY="nohidden" ;;
 			*)
-				bash -c "$HELP_STAR_SECTION"
-				exit 1
+				die_with_octocat "Invalid command: $(bash -c "$HELP_STAR_SECTION")"
 				;;
 			esac
 		done
@@ -841,8 +823,7 @@ while [ $# -gt 0 ]; do
 		break
 		;;
 	*)
-		bash -c "$HELP_GENERAL"
-		exit 1
+		die_with_octocat "Invalid command: $(bash -c "$HELP_GENERAL")"
 		;;
 	esac
 done
